language: generic
sudo: required

services:
    - docker

before_install:
    - docker build .

script:
    - docker run -e CI=true themorningcompany/analytical-website npm run test

after_success:
    - docker build .
