language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t pepperlola/analytical-website .

after_success:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL
after_failure:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh failure $WEBHOOK_URL

# script:
#     - docker run -e CI=true pepperlola/analytical-website npm run test

after_success:
    - docker build .
