language: generic
sudo: required

services:
    - docker

before_install:
    - docker build .

script:
    - docker run -e CI=true npm run test

after_success:
    - docker build -t indreklasn/my-react-docker-app .
