language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t TheMorningCompany/analytical-website .

script:
    - docker run -e CI=true TheMorningCompany/analytical-website npm run test

after_success:
    - docker build -t indreklasn/my-react-docker-app .
